### ISSUE TITLE
html looks good

### ISSUE THREAD

**Issue by rimmesbe** [annchelic/capstone#1]
Your html looks good, well structured. I like the use of semantic tags, keep expanding on that. Like here you should use `<header>`. Here is a good article with structuring a page with semantic tags:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/annchelic/capstone/blob/master/index.html#L10

**Comment by annchelic** [comment]
changed to header
